/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  "tutorialSidebar": [
    'intro',
    {
      type: 'category',
      label: 'Comprensión lectora',
      items: [
        'comprensión-lectora/introducción',
        'comprensión-lectora/material',
        'comprensión-lectora/etapa-01',
        'comprensión-lectora/etapa-02',
        'comprensión-lectora/etapa-03',
        'comprensión-lectora/etapa-04',
        'comprensión-lectora/etapa-05',
        'comprensión-lectora/etapa-06',
        'comprensión-lectora/etapa-07',
        'comprensión-lectora/etapa-08',
        'comprensión-lectora/etapa-09',
        'comprensión-lectora/etapa-10',
        'comprensión-lectora/etapa-11',
        'comprensión-lectora/etapa-12',
        'comprensión-lectora/conclusión',
      ],
    },
  ]

};

export default sidebars;
