/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  "tutorialSidebar": [
    {
      type: 'category',
      label: 'Educación',
      items: [
        {
          type: 'category',
          label: 'Comprensión lectora',
          items: [
            'educacion/comprension-lectora/introduccion',
            'educacion/comprension-lectora/material',
            'educacion/comprension-lectora/etapa-01',
            'educacion/comprension-lectora/etapa-02',
            'educacion/comprension-lectora/etapa-03',
            'educacion/comprension-lectora/etapa-04',
            'educacion/comprension-lectora/etapa-05',
            'educacion/comprension-lectora/etapa-06',
            'educacion/comprension-lectora/etapa-07',
            'educacion/comprension-lectora/etapa-08',
            'educacion/comprension-lectora/etapa-09',
            'educacion/comprension-lectora/etapa-10',
            'educacion/comprension-lectora/etapa-11',
            'educacion/comprension-lectora/etapa-12',
            'educacion/comprension-lectora/conclusion',
          ],
        }
      ]
    },
    'contacto'
  ]

};

export default sidebars;
